# Generated by Django 2.2.28 on 2023-08-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_id',
            field=models.CharField(default='1234qwe', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
