# Generated by Django 2.2.28 on 2023-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20230815_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='krish@k.com', max_length=254),
            preserve_default=False,
        ),
    ]
