# Generated by Django 2.2.28 on 2023-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragentlog',
            old_name='user_agent',
            new_name='name',
        ),
        migrations.AddField(
            model_name='useragentlog',
            name='details',
            field=models.TextField(default=[]),
        ),
    ]
