# Generated by Django 2.2.28 on 2023-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20230827_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.TextField(default=[]),
        ),
    ]
